#!/bin/bash -l
#SBATCH -C haswell
#SBATCH -p debug      # change this option for non-debug runs
#SBATCH -N 32         # adjust the number of nodes per test (e.g. start with 1, 2, ...)
#SBATCH -t 00:10:00   # adjust the amount of time as necessary
#SBATCH -J mpi32
#SBATCH -o mpi32.%j.stdout
#SBATCH -e mpi32.%j.error

srun -N 32 -n 32 ./mpi -n 4000 -o mpi.txt  # adjust -n here as well
srun -N 32 -n 16 ./mpi -n 4000 -o mpi.txt  # adjust -n here as well
srun -N 32 -n 8 ./mpi -n 4000 -o mpi.txt  # adjust -n here as well
srun -N 32 -n 4 ./mpi -n 4000 -o mpi.txt  # adjust -n here as well
srun -N 32 -n 2 ./mpi -n 4000 -o mpi.txt  # adjust -n here as well

srun -N 32 -n 32 ./mpi -n 2000 -o mpi.txt  # adjust -n here as well
srun -N 32 -n 32 ./mpi -n 4000 -o mpi.txt  # adjust -n here as well
srun -N 32 -n 32 ./mpi -n 8000 -o mpi.txt  # adjust -n here as well
srun -N 32 -n 32 ./mpi -n 16000 -o mpi.txt  # adjust -n here as well
