#!/bin/bash -l
#SBATCH -C haswell
#SBATCH -p debug      # change this option for non-debug runs
#SBATCH -N 1          # you'll never need more than 1 node for the openmp code
#SBATCH -t 00:10:00   # adjust the amount of time as necessary
#SBATCH -J openmp32
#SBATCH -o openmp32.%j.stdout
#SBATCH -e openmp32.%j.error

export OMP_NUM_THREADS=1
srun -N 1 -n 1 -c 1 ./openmp -n 500 -o openmp.txt
export OMP_NUM_THREADS=2
srun -N 1 -n 1 -c 2 ./openmp -n 500 -o openmp.txt
export OMP_NUM_THREADS=3
srun -N 1 -n 1 -c 3 ./openmp -n 500 -o openmp.txt
export OMP_NUM_THREADS=4
srun -N 1 -n 1 -c 4 ./openmp -n 500 -o openmp.txt
export OMP_NUM_THREADS=5
srun -N 1 -n 1 -c 5 ./openmp -n 500 -o openmp.txt
export OMP_NUM_THREADS=8
srun -N 1 -n 1 -c 8 ./openmp -n 500 -o openmp.txt
export OMP_NUM_THREADS=16
srun -N 1 -n 1 -c 16 ./openmp -n 500 -o openmp.txt
export OMP_NUM_THREADS=32
srun -N 1 -n 1 -c 32 ./openmp -n 500 -o openmp.txt

export OMP_NUM_THREADS=2
srun -N 1 -n 1 -c 2 ./openmp -n 500 -o openmp.txt
export OMP_NUM_THREADS=4
srun -N 1 -n 1 -c 4 ./openmp -n 1000 -o openmp.txt
export OMP_NUM_THREADS=8
srun -N 1 -n 1 -c 8 ./openmp -n 2000 -o openmp.txt
export OMP_NUM_THREADS=16
srun -N 1 -n 1 -c 16 ./openmp -n 4000 -o openmp.txt
export OMP_NUM_THREADS=32
srun -N 1 -n 1 -c 32 ./openmp -n 8000 -o openmp.txt
